package backend.academy.linktracker.scrapper.logging;

public enum LogEvent {
    TRACKED_LINK_RESOLVED,
    TRACKED_LINK_DELETED,
    TRACKED_LINK_CREATION_FAILED,
    SUBSCRIPTION_ADD_FAILED,
    SUBSCRIPTION_ADDED,
    SUBSCRIPTION_REMOVE_CHAT_NOT_FOUND,
    SUBSCRIPTION_REMOVE_TRACKED_LINK_NOT_FOUND,
    SUBSCRIPTION_REMOVED,
    SUBSCRIPTION_LIST_FAILED,
    SUBSCRIPTION_LIST_LOADED,
    SUBSCRIPTION_ADD_REJECTED,
    SUBSCRIPTION_REMOVE_REJECTED,
    TELEGRAM_CHAT_REGISTER_FAILED,
    TELEGRAM_CHAT_REGISTERED,
    TELEGRAM_CHAT_UNREGISTER_FAILED,
    TELEGRAM_CHAT_UNREGISTERED,
    LINK_UPDATE_CHECK_STARTED,
    REPOSITORY_POLLING_FAILED,
    LINK_UPDATE_CHECK_FAILED,
    LINK_UPDATE_SKIPPED,
    LINK_UPDATE_NOTIFICATION,
    BOT_RESPONSE_FAILED,
    REQUEST_PROCESSING_FAILED
}
