package backend.academy.linktracker.bot.logging;

public enum LogEvent {
    UPDATE_IGNORED,
    COMMAND_DISPATCH,
    ERROR_SENDING_RESPONSE,
    TELEGRAM_SEND_SKIPPED,
    TELEGRAM_SET_MY_COMMANDS_FAILED,
    TELEGRAM_SET_MY_COMMANDS_OK,
    LINK_UPDATE_NOTIFICATION,
    TRACK_DIALOG_STARTED,
    TRACK_DIALOG_CANCELLED,
    TRACK_DIALOG_MESSAGE_PROCESSED,
    TRACK_DIALOG_MESSAGE_IGNORED,
    HANDLED_EXCEPTION,
    UNHANDLED_EXCEPTION,
    TELEGRAM_CLIENT_CONFIGURED
}
